query {
  devices(location: ["Abingdon", "Vancouver"], manufacturer:"Sophos", tags: "SFOS", tags__n:"Auxillary", status:"Active") {
    name
    location {
      parent {
        parent {
          name
        }
      }
    }
  }
}