apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-06384e2efc05b3037,subnet-00789cad45b627e72
  labels:
    app: fwaudit
spec:
  type: {{ .Values.fwaudit.service.type }}
  ports:
    - port: {{ .Values.fwaudit.service.port }}
      targetPort: {{ .Values.fwaudit.service.targetPort }}
  selector:
    app: fwaudit